name: Create Release

on:
  workflow_dispatch:
    inputs:
      main_branch:
        required: true
        type: string
        default: 'main'
 
      release_version:
        description: 'Set version to release'
        required: true
        type: string
permissions:
    actions: write
    contents: write

jobs:
  release:
    name: Create A Release
    runs-on: ubuntu-latest
    permissions:
        actions: write
        contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        #   token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "Ashmanix"
          git config user.email "theashmanix@gmail.com"

      - name: Commit Changes
        run: |
          if [ ! -f "versions.txt" ]; then
            # Create the file and insert the JSON object
            touch versions.txt
          fi
          echo "${{ inputs.release_version}}" >> versions.txt
          git add versions.txt
          git commit -m "version update to v${{ inputs.release_version }}"

      - name: Create Tag
        run: |
          git tag -a v${{ inputs.release_version }} -m "Release v${{ inputs.release_version }}"
        
      - name: Merge develop into main branch
        run: |
          git checkout ${{ inputs.main_branch }}
          git merge develop --no-ff -m "Merge develop"
  
      - name: Push changes
        run: git push --all --follow-tags
